### ISSUE TITLE
Page aside element images 

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/kunta-api-www-mikkeli#21]
As an user i would like that content page aside element images would be take all available vertical space

**Comment by anttileppa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Voiko sivupalkkiin laittaaa kuvan?](https://trello.com/c/RzpYvfEV/27-voiko-sivupalkkiin-laittaaa-kuvan)

**Comment by hkurhinen** [comment]
fixed in https://github.com/Metatavu/kunta-api-www-mikkeli/commit/eba8b3aa8cc09cfba9dfb4bde9c128dcdf4dced2
