### ISSUE TITLE
In news menu listing - is shown as &#8211;

### ISSUE THREAD

**Issue by hkurhinen** [Metatavu/kunta-api-www-mikkeli#220]

**Comment by anttileppa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [uutisissa "-" viiva näkyy merkkijonona &#8211;](https://trello.com/c/yD89kIpR/179-uutisissa-viiva-n%C3%A4kyy-merkkijonona-8211)

**Comment by anttileppa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rivitysongelma: Päätöksenteko -> Lautakunnat: kaupunkiympäristölautakunta. Valikon teksti ei rivity, vaan valuu sisältöalueen päälle tietyillä resoluutioilla.](https://trello.com/c/tRG8dfjJ/176-rivitysongelma-p%C3%A4%C3%A4t%C3%B6ksenteko-lautakunnat-kaupunkiymp%C3%A4rist%C3%B6lautakunta-valikon-teksti-ei-rivity-vaan-valuu-sis%C3%A4lt%C3%B6alueen-p%C3%A4%C3%A4lle-ti)
