### ISSUE TITLE
Hide sidebar when it has no contents

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/kunta-api-www-mikkeli#28]
As an user i would like that sidebar would be hidden if it contains to data

**Comment by jerelauha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sivupalkin toiminnallisuus: jos ei sisältöä, niin palkkia ei näytetä?](https://trello.com/c/DHK5Xq52/23-sivupalkin-toiminnallisuus-jos-ei-sisaltoa-niin-palkkia-ei-nayteta)

**Comment by jerelauha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sivupalkin toiminnallisuus: jos ei sisältöä, niin palkkia ei näytetä?](https://trello.com/c/DHK5Xq52/23-sivupalkin-toiminnallisuus-jos-ei-sisaltoa-niin-palkkia-ei-nayteta)
