### ISSUE TITLE
Jobs page

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/kunta-api-www-mikkeli#32]
As an user i would like to see jobs listed in Mikkeli's site instead of Kunta Rekry

**Comment by jerelauha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) kunta-rekry: työpaikan linkkiä siirrytään alasivulle lukemaan tarkemmin + katso kaikki -linkki -> alasivuille kaikkien listaus, ei siirtymää kuntarekryyn suoraan](https://trello.com/c/AHWfn35a/13-2-kunta-rekry-tyopaikan-linkkia-siirrytaan-alasivulle-lukemaan-tarkemmin-katso-kaikki-linkki-alasivuille-kaikkien-listaus-ei-sii)
