### ISSUE TITLE
Tile text shortening

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/kunta-api-www-mikkeli#33]
Instead of ellipsis shortening use smaller font when tile image texts to dont fit the screen

**Comment by jerelauha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) joillakin resoluutioilla pikkubannerien otsikkoon tulee ... - saako siihen tavutuksen tms. ratkaisun?](https://trello.com/c/FvPYvN50/47-1-joillakin-resoluutioilla-pikkubannerien-otsikkoon-tulee-saako-siihen-tavutuksen-tms-ratkaisun)
