### ISSUE TITLE
Osallistu ja vaikuta

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/kunta-api-www-mikkeli#35]
As a manager i would like to be able to edit osallistu ja vaikuta texts in management

**Comment by jerelauha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Osallistu ja vaikuta -osion toteutus](https://trello.com/c/SowSmqmL/54-osallistu-ja-vaikuta-osion-toteutus)
