### ISSUE TITLE
Open page menu children when menu active

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/kunta-api-www-mikkeli#36]
As an user i would like that page menu children would be visible when i have opened the parent menu

**Comment by jerelauha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Alavalikko avautumaan linkistä, ei pelkästään + merkistä?](https://trello.com/c/HEiDE5d8/53-alavalikko-avautumaan-linkista-ei-pelkastaan-merkista)
